In [2]:
import numpy as np

In [6]:
#Scenario 1

a1 = np.arange(8).reshape(2, 4)
a2 = np.arange(8, 16).reshape(2, 4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [8]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [14]:
#Scenario 2 : Shape not Same

a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)

print(a3, a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [12]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

#The second array got added to all the rows

**Broadcasting**

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly he same shape, then these operations are smoothly performed.

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, opeartions on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

**Rules for Broadcasting**

In [29]:
#IF x = m and y = n, operation will take place

a1 = np.arange(8).reshape(2, 4)
a2 = np.arange(8, 16).reshape(2, 4)

a1 + a2


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [31]:
#If x = 1 and y = n, operation will take place (same dimensions)

a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)

a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [37]:
#If y = 1 and x = n, operation will take place (same dimension)

a5 = np.arange(12).reshape(4, 3)
a6 = np.arange(4).reshape(4, 1)

print(a5, a6)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] [[0]
 [1]
 [2]
 [3]]


In [39]:
a5+a6

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [41]:
#If x = 1 and y!=n then operation WILL NOT TAKE PLACE

a7 = np.arange(3).reshape(1, 3)
a8 = np.arange(16).reshape(4, 4)

print(a7, a8)

[[0 1 2]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [43]:
a7+a8

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [47]:
# If x = 1 and n = 1 then y == m, then operation will take place

a9 = np.arange(3).reshape(1, 3)
a10 = np.arange(3).reshape(3, 1)

print(a9, a10)

[[0 1 2]] [[0]
 [1]
 [2]]


In [49]:
a9 + a10

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [51]:
# If x = 1 and y = 1, then operation will take place no matter what

a11 = np.arange(1).reshape(1, 1)
a12 = np.arange(20).reshape(4, 5)

print(a11, a12)

[[0]] [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [53]:
a11 + a12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])