In [2]:
import numpy as np

In [10]:
np.random.random()  #any random value between 0 and 1

0.8446795994849069

In [19]:
#If we want same random value again and again

np.random.seed(1)
np.random.random()

0.417022004702574

In [41]:
#Random value between a range

np.random.seed(1)
np.random.uniform(2, 15)

7.421286061133462

In [51]:
#10 random values between 1 and 100

np.random.uniform(1, 100, 10)

array([35.42882011, 75.33039821, 72.87380055, 88.44730303, 62.7435485 ,
       75.34330097, 35.54093586, 27.72286128, 89.6927356 , 43.3810278 ])

In [53]:
np.random.uniform(1, 100, 10).reshape(2, 5)

array([[96.51916467, 66.68070828, 62.5478763 , 12.35985132, 94.99943661],
       [45.54130121, 58.26057182, 41.40554347, 24.46567104, 90.43457254]])

In [59]:
np.random.randint(1, 100, 10).reshape(5, 2)

array([[54, 85],
       [11, 97],
       [56, 62],
       [57, 90],
       [22, 97]])

In [65]:
a = np.random.randint(1, 10, 6)
a

array([9, 3, 8, 6, 6, 5])

In [73]:
a.max()

9

In [69]:
np.max(a)

9

In [71]:
np.min(a)

3

ARGMAX attribute

In [77]:
np.argmax(a)  #Gives the index of the maximumvalue

0

In [79]:
a[np.argmax(a)]

9

In [81]:
np.argmin(a)

1

In [85]:
a[np.argmin(a)]

3

In [90]:
a = np.random.randint(1, 20, 10)
a

array([17, 11, 14,  4,  3, 15, 15,  1, 12,  4])

In [96]:
# Replacing odd values with -1 but the array permanently changes

a[a%2==1]= -1
a

array([-1, -1, 14,  4, -1, -1, -1, -1, 12,  4])

In [102]:
a = np.random.randint(1, 50, 10)
a

array([21, 45, 16, 31, 28, 15, 20, 27, 44, 23])

In [108]:
#Replacing values without changing original array
# where(condition, result if True,result if False)

out = np.where(a%2 ==1, -1, a)
out

array([-1, -1, 16, -1, 28, -1, 20, -1, 44, -1])

In [106]:
a

array([21, 45, 16, 31, 28, 15, 20, 27, 44, 23])

In [110]:
a = np.random.randint(1, 100, 15)
a

array([ 8, 54, 48, 61, 35, 33, 20, 68, 25, 84, 95, 39, 48,  6, 80])

In [112]:
np.sort(a)  #sorting array

array([ 6,  8, 20, 25, 33, 35, 39, 48, 48, 54, 61, 68, 80, 84, 95])

In [122]:
np.percentile(a, 99.8)

94.692

**Percentile**

if we give percentile as 99.5:
It denotes that

> you're less than 100% of the score
> also, you're ahead 99.5% elements in the array